# Generated by Django 4.2.7 on 2026-01-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du projet"),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Entreprise/Client"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="portfolio/", verbose_name="Image du projet"
                    ),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, verbose_name="URL du site web"),
                ),
                (
                    "detail_url",
                    models.URLField(
                        blank=True, verbose_name="URL de détail (optionnel)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vitrine", "Site vitrine"),
                            ("ecommerce", "E-commerce"),
                            ("institutionnel", "Institutionnel"),
                            ("landing", "Landing page"),
                            ("refonte", "Refonte"),
                            ("autre", "Autre"),
                        ],
                        default="vitrine",
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet portfolio",
                "verbose_name_plural": "Projets portfolio",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
