# Generated by Django 4.2.7 on 2026-02-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_technology"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="anonymous_cta/", verbose_name="Image du cercle"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Section CTA Anonyme",
                "verbose_name_plural": "Section CTA Anonyme",
                "ordering": ["-updated_at"],
            },
        ),
    ]
