# Generated by Django 4.2.7 on 2026-02-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_anonymouscta"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Format: +2266474200 (avec indicatif pays, sans espaces)",
                        max_length=20,
                        verbose_name="Numéro WhatsApp",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        default="Bonjour, je souhaite obtenir plus d'informations sur vos services.",
                        help_text="Message qui sera pré-rempli lors du clic sur le bouton",
                        max_length=200,
                        verbose_name="Message par défaut",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration WhatsApp",
                "verbose_name_plural": "Configuration WhatsApp",
                "ordering": ["-updated_at"],
            },
        ),
    ]
