# Generated by Django 4.2.7 on 2026-02-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_whatsappconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Réponse")),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "question"],
            },
        ),
    ]
