# Generated by Django 4.2.7 on 2026-02-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projects_count",
                    models.IntegerField(default=0, verbose_name="Projets réalisés"),
                ),
                (
                    "years_experience",
                    models.IntegerField(default=0, verbose_name="Années d'expérience"),
                ),
                (
                    "client_satisfaction",
                    models.IntegerField(
                        default=0,
                        help_text="Pourcentage de satisfaction client (0-100)",
                        verbose_name="% Clients satisfaits",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistiques de l'entreprise",
                "verbose_name_plural": "Statistiques de l'entreprise",
                "ordering": ["-updated_at"],
            },
        ),
    ]
