# Generated by Django 4.2.7 on 2026-02-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_companystats"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(max_length=500, verbose_name="Chemin de la page"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Adresse IP")),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="Pays"),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Code pays"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("referer", models.URLField(blank=True, verbose_name="Référent")),
                ("is_bot", models.BooleanField(default=False, verbose_name="Bot")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de visite"
                    ),
                ),
            ],
            options={
                "verbose_name": "Visite",
                "verbose_name_plural": "Visites",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="core_pagevi_created_4d45f9_idx"
                    ),
                    models.Index(fields=["path"], name="core_pagevi_path_582912_idx"),
                    models.Index(
                        fields=["country_code"], name="core_pagevi_country_bf9550_idx"
                    ),
                ],
            },
        ),
    ]
