# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_pageview"),
    ]

    operations = [
        migrations.AddField(
            model_name="companystats",
            name="support_24_7",
            field=models.IntegerField(
                default=24,
                help_text="Nombre affiché pour la stat « Support 24/7 » (ex: 24)",
                verbose_name="Support 24/7",
            ),
        ),
    ]
