# Generated by Django 4.2.7 on 2026-02-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_companystats_support_24_7"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Question")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date"),
                ),
            ],
            options={
                "verbose_name": "Question assistant",
                "verbose_name_plural": "Questions posées à l'assistant",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="core_assist_created_dc9c6e_idx"
                    )
                ],
            },
        ),
    ]
