# Generated by Django 4.2.7 on 2026-02-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_pagebanner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagebanner",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Page d'accueil"),
                    ("services", "Services (toutes les pages du sous-menu Services)"),
                    ("maintenance", "Maintenance de site web"),
                ],
                max_length=50,
                verbose_name="Page",
            ),
        ),
    ]
