# Generated by Django 4.2.7 on 2026-03-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_pagebanner_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageview",
            name="session_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=40, verbose_name="Clé de session"
            ),
        ),
        migrations.AlterField(
            model_name="pageview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date et heure de visite"
            ),
        ),
        migrations.AlterField(
            model_name="pageview",
            name="referer",
            field=models.TextField(blank=True, verbose_name="Provenance (référent)"),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["session_key"], name="core_pagevi_session_3251c9_idx"
            ),
        ),
    ]
