# Generated by Django 4.2.7 on 2026-03-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_pageview_session_key_and_referer_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageview",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("desktop", "Ordinateur"),
                    ("mobile", "Mobile"),
                    ("tablet", "Tablette"),
                    ("other", "Autre"),
                ],
                db_index=True,
                default="other",
                max_length=20,
                verbose_name="Type d'appareil",
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["device_type"], name="core_pagevi_device__96a861_idx"
            ),
        ),
    ]
